### ISSUE TITLE
How to setup Database schema and initial setup on Superbase?

### ISSUE THREAD

**Issue by kennguyen887** [adityayaduvanshi/Full-Stack-Music-Web-App#3]
Thank you so much for sharing this project. However, we can't run the project because the code requires API configurations and demo data on Supabase. Could you kindly share "How to set up Database schema and initial setup on Supabase?"

**Comment by adityayaduvanshi** [comment]
Thanks. I will upload the video or documentation for database schema

**Comment by vladblaj** [comment]
Hello and many thanks for this project. I would also be interested in the database schema. Thank in advance!

**Comment by adityayaduvanshi** [comment]
Please check sql schema. Let me know if you need any help.  [https://github.com/adityayaduvanshi/Full-Stack-Music-Web-App/blob/067c88c7708b5b46d2ddb2dd013c1fac6690a253/database.sql]

**Comment by adityayaduvanshi** [comment]
Please check sql schema [database.sql](https://github.com/adityayaduvanshi/Full-Stack-Music-Web-App/blob/067c88c7708b5b46d2ddb2dd013c1fac6690a253/database.sql). Let me know if you need any help.
